# version: "3.8"

# services:
#   app:
#     image: registry.gitlab.com/q347/starlette_crawl_code:v0.3
#     container_name: starlette_crawl_code
#     command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
#     ports:
#       - "5001:8000"
#     restart: always
#     volumes:
#       - ./app:/app

version: "3.8"

services:
  app:
    image: registry.gitlab.com/q347/starlette_crawl_code:v0.4
    container_name: starlette_crawl_code
    command: gunicorn --worker-class=uvicorn.workers.UvicornWorker --log-level warning --worker-connections=1000 --workers=3 --bind 0.0.0.0:5000 app:app
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - "5001:5000"
    environment:
      VIRTUAL_HOST: giaca.qbtool.xyz
      VIRTUAL_PORT: 5000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  default:
    external:
      name: b_nginx_network
